### ISSUE TITLE
Some letters not rendering properly

### ISSUE THREAD

**Issue by dthorrington** [AverageMaker/ZeroSeg#5]
Cheers for this repo, it's a great little project to play with. This was my first use of a soldering iron since school days.

I've noticed that some letters don't render properly on my display. Is this a problem with my assembly or an issue with the display in general not rendering certain letters correctly? I suspect the former, but best check first.

The letters that cannot be rendered are k, m, w, x and their upper-case equivalents. The display replaces them with underscores.

**Comment by rm-hull** [comment]
It's **not** a problem with your assembly, and is by design: with only seven fixed segments, it is not really possible to easily represent 'M' (or any of the other characters you mentioned), so a decision was taken to render with an underscore instead. Keep in mind these devices were originally intended for numeric display.

> Try using https://github.com/rm-hull/luma.led_matrix instead - this is actively maintained (by me & a few others), supports py2/3, has documentation & automated tests, installs from pypi, etc. It was the original library that @averagemanvspi forked for this repo. Things have moved on considerably in the original since the fork occurred however.
